config/routes.rb
Freetime::Application.routes.draw do

  root 'hobbies#index'

  resources :hobbies

end

app/models/hobby.rb
class Hobby < ActiveRecord::Base
	validates :hobby_name, :presence => true, :length => { :maximum => 150, :minimum => 3 }
	validates :author, :presence => true, :length => { :maximum => 50, :minimum => 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController

	def index
		@hobbies = Hobby.paginate(:page => params[:page], :per_page => 5)
	end

	def new
		@hobby = Hobby.new
	end

	def create
		@hobby = Hobby.create(hobby_params)
		redirect_to root_path
	end

	private

	def hobby_params
		params.require(:hobby).permit(:hobby_name, :description, :author)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/index.html.erb
<% @hobbies.each do |hobby| %>
	<div class="booyah-box col-xs-10 col-xs-offset-1">
		<h1><%= hobby.hobby_name %></h1><br />
		<i><%= hobby.description %></i><br /><br />
		<div class="pull-right">
			<p>-<%= hobby.author %></p>
		</div>
	</div>
<% end %>

<%= will_paginate @hobbies %>

app/views/hobbies/new.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
	<h1>Enter Your Own Hobby</h1>
	<%= simple_form_for @hobby do |f| %>
	  <%= f.input :hobby_name %>
	  <%= f.input :description %>
	  <%= f.input :author %>
	  <br />
	  <%= f.submit 'Create', :class => 'btn btn-primary' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Freetime</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'FreeTime', root_path, :class => 'navbar-brand' %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li>
        	<%= link_to new_hobby_path do %>
        	<i class="glyphicon glyphicon-plus-sign"></i>
        	New Hobby
        	<% end %>
        </li>
      </ul>
        <ul class="nav navbar-nav navbar-right">
        	<li><a href="#">Link</a></li>
        </li>
      </ul>
   
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>




<%= yield %>

</body>
</html>